=== Tpotmon/gallery.tpotmon.com/.astro/collections/action-cards.schema.json
{
  "$ref": "#/definitions/action-cards",
  "definitions": {
    "action-cards": {
      "type": "object",
      "properties": {
        "id": {
          "type": "number"
        },
        "title": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "effect": {
          "type": "string"
        },
        "flavor": {
          "type": "string"
        },
        "imageUrl": {
          "type": "string"
        },
        "rarity": {
          "type": "string"
        },
        "inspiredBy": {
          "type": "string",
          "format": "uri"
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "title",
        "type",
        "effect",
        "flavor",
        "imageUrl",
        "rarity"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== Tpotmon/gallery.tpotmon.com/src/content/action-cards/14.json
{
  "id": 14,
  "title": "Yuri Posting",
  "type": "Action",
  "effect": "Gain +2 EP next turn. Opponent must reveal hidden action cards for 1 turn.",
  "flavor": "No likes, no comments, just bookmarks.",
  "imageUrl": "/action-cards/yuri-posting.png",
  "rarity": "Common",
  "inspiredBy": "https://x.com/KIRBARA2000/status/1936821952716607912"
}

=== Tpotmon/gallery.tpotmon.com/src/content/action-cards/28.json
{
  "id": 28,
  "title": "I still think about this",
  "type": "Action",
  "effect": "The next time you attack with the same card, add +20 damage. This effect can only be used once per card per game.",
  "flavor": "Some tweets never leave your mind. Neither do their consequences.",
  "imageUrl": "/action-cards/i-still-think-about-this.png",
  "rarity": "Common"
}
